spring:
  application:
    name: pet-net-server
logging:
  level:
    root: DEBUG
server:
  port: 8080
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    property:
      prefix: ENC(
      suffix: )